wrote click handler for About Us link in footer
andrayantelo/ivys_attic pull request #59
Opened 2017-05-08 20:53 UTC by andrayantelo

2017-05-08 23:40 UTC, johntyree requested changes

2017-05-08 23:40 UTC, johntyree commented on docs/index.html
> +                        <a id="hours-location-link" href="#">Hours & Location</a>
You might need to html-escape this ampersand for it to work everywhere.

2017-05-09 20:44 UTC, andrayantelo commented on docs/index.html
> +                        <a id="hours-location-link" href="#">Hours & Location</a>
What do you mean?

2017-05-10 21:24 UTC, andrayantelo commented on docs/index.html
> +                        <a id="hours-location-link" href="#">Hours & Location</a>
@johntyree

2017-05-20 23:47 UTC, johntyree commented on docs/index.html
> +                        <a id="hours-location-link" href="#">Hours & Location</a>
https://www.w3.org/International/questions/qa-escapes#use

2017-05-20 23:48 UTC, johntyree requested changes

2017-05-20 23:48 UTC, johntyree commented on docs/ivys.js
> +    var div;
Why is this here?

2017-05-22 17:33 UTC, andrayantelo commented on docs/index.html
> +                        <a id="hours-location-link" href="#">Hours & Location</a>
Got it.

2017-05-22 17:34 UTC, andrayantelo commented on docs/ivys.js
> +    var div;
Why is what here? The function? @johntyree

2017-05-28 04:46 UTC, johntyree commented on docs/ivys.js
> +    var div;
The div declaration, but I guess jslint just wants them all up front

2017-05-28 04:46 UTC, johntyree requested changes

2017-05-28 04:46 UTC, johntyree commented on docs/index.html
> +                        <a id="hours-location-link" href="#">Hours &amp Location</a>
Missing a ';' I think.

2017-05-30 16:48 UTC, andrayantelo commented on docs/index.html
> +                        <a id="hours-location-link" href="#">Hours &amp Location</a>
Added it.

2017-05-31 04:24 UTC, johntyree approved these changes

2017-05-31 21:03 UTC, merged